### ISSUE TITLE
Improve filtering logic

### ISSUE THREAD

**Issue by ligen-ua** [oleks-yehorov/PathHider#4]
There are two items there

1. HideFiles contains arithmetic logic which looks potentially vulnerable, it relies on valid user input. 
I would recommend to introduce more bounds checks there, write tests with incorrect data, try to fuzz it.

2. HideFiles uses QueryDirectory.DirectoryBuffer exclusively

See MSDN on it:

> DirectoryBuffer
> Pointer to a caller-supplied output buffer that receives the requested information about the contents of the directory. This member is optional and can be NULL if a MDL is provided in QueryDirectory.MdlAddress. See Remarks.

https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-directory-control

Another potentially useful sample:
https://github.com/microsoft/Windows-driver-samples/blob/b8d3abcd822aafc27af851f7ec6b8938b21e57b5/filesys/miniFilter/swapBuffers/swapBuffers.c

**Comment by oleks-yehorov** [comment]
This is an excellent point, I did not realize how potentially dangerous to deal with user buffers. I have found this good advice on how to handle such cases. I did the changes for the first part of the issue, now I will close this one and create a new one for the second part (as I believe they should have been two different isssues)
 
> Never Trust Buffers

Filter drivers are forced to endure a remarkably hostile environment, both from their neighbors (other filter drivers) as well as those that are inherently untrusted (any user mode code). A single mistake in a file system filter driver can create a potential "time bomb" waiting to happen.

User Buffers are the most commonly identified "risk factor" when it comes to buffer management. Despite that, we still routinely see filters that fail to take the two necessary steps for protecting against user buffers. First, you must ensure that a user buffer really is within the user portion of the address space. This is performed by probing the address, normally using ProbeForRead or ProbeForWrite.

Probing a user buffer only ensures it is in the user's address space, however. If it is invalid at that point in time the probe will work, but this call does nothing to ensure the address remains valid. Thus, the second key part of buffer handling is to ensure any access to it is protected with a structured exception handler. Microsoft provides their own custom handler and it is invoked using special extensions implemented by the C compiler used in the WDK environment. This is done using __try and __except.

Both of these steps are essential to ensuring correct user buffer handling.

In addition, file system filter drivers must deal with the pragmatic issue that they may be handed invalid kernel data structures. The harsh reality is that it is not uncommon for other kernel components to pass along invalid structures. Mini-filters are somewhat protected against this, since invalid structures passed into filter manager will cause filter manager to crash, not the mini-filter. Despite this, if you are the only mini-filter on the system it won't crash without your filter and it will crash with your filter (and we all know that this means it must be "your fault").

Thus, what we generally suggest - as much as possible - is to carefully validate your own data structures. While not guaranteed, we've used this technique to detect erroneous situations numerous times. In our experience it is better to use "deprecated" functions like MmIsNonPagedSystem AddressValid (which is of dubious value) to add even a modest amount of robustness to our code. This is pragmatic - if the system crashes in our driver, we will be blamed for the crash. If we can instead return an error and it crashes in another driver, it will become the problem of that other driver writer. Remember, when someone types "!analyze -v", it will blame the first non-Microsoft driver on the stack. Hence, it-s better to not be on the stack, at least from a support overhead burden.
